### 회원 가입 API
POST localhost:8080/api/members/signup
Content-Type: application/json

{
  "email": "hong-gd@gmail.com",
  "password": "password",
  "name": "홍길동",
  "nickname": "동에번쩍 서에번쩍"
}

### 로그인 API
POST localhost:8080/api/members/signin
Content-Type: application/json

{
  "email": "hong-gd@gmail.com",
  "password": "password"
}

### 마이페이지 API
GET localhost:8080/api/members/my-page
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzU0MTE4OTUxfQ.5xc45HuQnPKMZBfc9CAsXMjIg6h3-xbDM2aYcAezLqE

